export const constants = {
  COUNTER_WRAPPER_CLASS: 'info-section__counter-wrapper',
  COUNTER_TITLE_CLASS: 'counter-wrapper__title',
  COUNTER_CLASS: 'info-section__counter',
  CLICK_WRAPPER_CLASS: 'info-section__click-wrapper',
  CLICK_TITLE_CLASS: 'click-wrapper__title',
  CLICK_CLASS: 'click-wrapper__clicks',
  CELL_ROW_TAG: 'div',
  CELL_ROW_CLASS: 'playground__row',
  CELL_TAG: 'cell-div',
  END_GAME_TEXT_CLASS: 'end-game-text',
  END_GAME_TEXT_WIN: 'YOU WIN! :)',
  END_GAME_TEXT_LOSE: 'YOU LOSE! :(',
  FONT_RATIO: 0.8,
  INFO_SECTION_CLASS: 'info-section',
  LAST_WINS_KEY: 'lastWins',
  LOCAL_DATA_KEY: 'currentState',
  // MAIN_TAG: 'div',
  EDITOR_CLASS: 'css-editor',
  VIEWER_CLASS: 'html-viewer',
  EDITOR_INFO_TEXT: `
  { <br>
    /* Styles would go here. */<br>
  }<br>
<br>
  /*<br>
    Type a number to skip to a level.<br>
    Ex &rarr; "5" for level 5<br>
  */
`,
  MAIN_CLASS: 'game-wrapper',
  PLAYGROUND_TAG: 'div',
  PLAYGROUND_CLASS: 'table-wrapper',
  SETTINGS_BTN_CLASS: 'info-section__settings-btn',
  SETTINGS_BTN: '➠',
  START_BTN_CLASS: 'start-btn',
  THEME_LIGHT: 'theme-light',
  // TIMER_CLASS: 'info-section__timer',
  // TIMER_MS_CLASS: 'info-section__timer-ms',
  // TIMER_SEC_CLASS: 'info-section__timer-sec',
  // TIMER_MIN_CLASS: 'info-section__timer-min',
};

export const menuClasses = {
  NAV_MENU: 'nav-menu',
  MENU_OVERLAY: 'menu-overlay',
  NAV_MENU_ACTIVE: 'nav_active',
  NAV_MENU_WRAPPER: 'nav-menu__wrapper',
  NAV_CLOSE_BTN: '✖',
  NAV_CLOSE_BTN_CLASS: 'nav-menu__close-btn',
  MENU_TITLE: 'nav-menu__title',
  MENU_TITLE_SCORE: 'title_score',
  SLIDER_WRAPPER: 'nav-slider-wrapper',
  WRAPPER_THEME: 'wrapper_theme',
  WRAPPER_SOUND: 'wrapper_sound',
  THEME_SLIDER: 'theme-slider',
  SOUND_SLIDER: 'sound-slider',
  MENU_LEVEL: 'menu-level',
  // LEVEL_ID_EASY: 'level-easy',
  // LEVEL_ID_MEDIUM: 'level-medium',
  // LEVEL_ID_HARD: 'level-hard',
  // LEVEL_ID_CUSTOM: 'level-custom',
  // CUSTOM_LEVEL_WRAP_CLASS: 'level-custom-wrapper',
  // CUSTOM_COLUMN_VAL: 'custom-column-val',
  // CUSTOM_ROW_VAL: 'custom-row-val',
  // CUSTOM_ROW_MAX: 30,
  // CUSTOM_ROW_MIN: 5,
  // CUSTOM_COLUMN_MAX: 30,
  // CUSTOM_COLUMN_MIN: 5,
  // CUSTOM_MINE_RATIO_MIN: 0.05,
  // CUSTOM_MINE_RATIO_MAX: 0.5,
  // CUSTOM_MINES_VAL: 'custom-mines-val',
  // CUSTOM_DONE_BTN: 'custom-done-btn',
  // CUSTOM_LEVEL_FORM: 'custom-level-form',
  WRONG_INPUT: 'wrong-input',
};

export const modalConst = {
  MODAL_OVERLAY: 'modal-overlay',
  MODAL_CLASS: 'modal-score',
  MODAL_TITLE: 'modal-score-title',
  MODAL_SCORE_TBL: 'modal-score-tbl',
  MODAL_RESULT_TITLES: 'score-tbl-titles',
  // RESULT_TITLE_DATE: 'Date',
  // RESULT_TITLE_SIZE: 'Size',
  // RESULT_TITLE_MINES: 'Mines',
  // RESULT_TITLE_TIME: 'Time',
  // RESULT_TITLE_CLICKS: 'Clicks',
  // MODAL_RESULT_ROW: 'score-tbl-results',
};
