export const constants = {
  START_BTN_CLASS: 'start-btn',
  COUNTER_WRAPPER_CLASS: 'info-section__counter-wrapper',
  COUNTER_TITLE_CLASS: 'counter-wrapper__title',
  COUNTER_CLASS: 'info-section__counter',
  CLICK_WRAPPER_CLASS: 'info-section__click-wrapper',
  CLICK_TITLE_CLASS: 'click-wrapper__title',
  CLICK_CLASS: 'click-wrapper__clicks',
  CELL_ROW_TAG: 'div',
  CELL_ROW_CLASS: 'playground__row',
  CELL_TAG: 'cell-div',
  FONT_RATIO: 0.8,
  INFO_SECTION_CLASS: 'info-section',
  LOCAL_DATA_KEY: 'currentState',
  MAIN_TAG: 'main',
  MAIN_CLASS: 'main',
  NAV_CLASS: 'nav-menu',
  PLAYGROUND_TAG: 'section',
  PLAYGROUND_CLASS: 'playground',
  SETTINGS_BTN_CLASS: 'info-section__settings-btn',
  TIMER_CLASS: 'info-section__timer',
  TIMER_MS_CLASS: 'info-section__timer-ms',
  TIMER_SEC_CLASS: 'info-section__timer-sec',
  TIMER_MIN_CLASS: 'info-section__timer-min',
};
