export const constants = {
  COUNTER_WRAPPER_CLASS: 'info-section__counter-wrapper',
  COUNTER_TITLE_CLASS: 'counter-wrapper__title',
  COUNTER_CLASS: 'info-section__counter',
  CLICK_WRAPPER_CLASS: 'info-section__click-wrapper',
  CLICK_TITLE_CLASS: 'click-wrapper__title',
  CLICK_CLASS: 'click-wrapper__clicks',
  CELL_ROW_TAG: 'div',
  CELL_ROW_CLASS: 'playground__row',
  CELL_TAG: 'cell-div',
  // DIV_MODAL_OVERLAY: 'modal-overlay',
  FONT_RATIO: 0.8,
  INFO_SECTION_CLASS: 'info-section',
  LAST_WINS_KEY: 'lastWins',
  LOCAL_DATA_KEY: 'currentState',
  MAIN_TAG: 'main',
  MAIN_CLASS: 'main',
  // MENU_NAV_CLASS: 'nav-menu',
  PLAYGROUND_TAG: 'section',
  PLAYGROUND_CLASS: 'playground',
  SETTINGS_BTN_CLASS: 'info-section__settings-btn',
  SETTINGS_BTN: '➠',
  START_BTN_CLASS: 'start-btn',
  TIMER_CLASS: 'info-section__timer',
  TIMER_MS_CLASS: 'info-section__timer-ms',
  TIMER_SEC_CLASS: 'info-section__timer-sec',
  TIMER_MIN_CLASS: 'info-section__timer-min',
};

export const menuClasses = {
  NAV_MENU: 'nav-menu',
  MENU_OVERLAY: 'menu-overlay',
  NAV_MENU_ACTIVE: 'nav_active',
  NAV_MENU_WRAPPER: 'nav-menu__wrapper',
  NAV_CLOSE_BTN: '✖',
  NAV_CLOSE_BTN_CLASS: 'nav-menu__close-btn',
  MENU_TITLE: 'nav-menu__title',
  MENU_TITLE_SCORE: 'title_score',
  // NAV_MENU_SCORE: 'nav-menu__score',
  // NAV_MENU_THEME: 'nav-menu__theme',
  SLIDER_WRAPPER: 'nav-slider-wrapper',
  WRAPPER_THEME: 'wrapper_theme',
  WRAPPER_SOUND: 'wrapper_sound',
  THEME_SLIDER: 'theme-slider',
  // THEME_LABEL: 'theme-label',
  SOUND_SLIDER: 'sound-slider',
  // SOUND_LABEL: 'sound-label',
  MENU_LEVEL: 'menu-level',
  // LEVEL_INPUT_WRAPPER: 'level-input-wrapper',
  // LEVEL_INPUT: 'level-input',
  LEVEL_ID_EASY: 'level-easy',
  LEVEL_ID_MEDIUM: 'level-medium',
  LEVEL_ID_HARD: 'level-hard',
  LEVEL_ID_CUSTOM: 'level-custom',
  CUSTOM_LEVEL_WRAP_CLASS: 'level-custom-wrapper',
  CUSTOM_COLUMN_VAL: 'custom-column-val',
  CUSTOM_ROW_VAL: 'custom-row-val',
  CUSTOM_MINES_VAL: 'custom-mines-val',
  CUSTOM_DONE_BTN: 'custom-done-btn',
  CUSTOM_LEVEL_FORM: 'custom-level-form',
};
